version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: etl_database
    environment:
      - POSTGRES_USER=etluser
      - POSTGRES_PASSWORD=etlpassword
      - POSTGRES_DB=etl_db
    ports:
      - "5432:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data 
    networks:
      - etl_network

volumes:
  db_data:

networks:
  etl_network:
    driver: bridge
